package com.relayra.role.domain;

public enum Permission {
  VIEW_CHANNEL,
  SEND_MESSAGES,
  ADD_REACTIONS,
  ATTACH_FILES,
  CREATE_INVITES,
  MANAGE_INVITES,
  MANAGE_CHANNELS,
  MANAGE_ROLES,
  MANAGE_MEMBERS,
  KICK_MEMBERS,
  BAN_MEMBERS,
  DELETE_MESSAGES,
  MANAGE_COMMUNITY,
  VIEW_AUDIT_LOG
}
